---
# ONLY to be used in a loop of client_keys.yml task

- name: "Generate '{{ item }}' client key"
  command: >-
    openssl req -nodes -newkey rsa:{{ openvpn_rsa_bits }} -keyout {{ item }}.key -out {{ item }}.csr
    -days 3650 -subj /CN=OpenVPN-Client-{{ inventory_hostname[:24] }}-{{ item[:24] }}/
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{ item }}.key"

- name: "Protect '{{ item }}' client key"
  file:
    path: "{{ openvpn_key_dir }}/{{ item }}.key"
    mode: 0400
  diff: false

- name: "Sign '{{ item }}' client key"
  command: openssl x509 -req -in {{ item }}.csr -out {{ item }}.crt -CA ca.crt -CAkey ca-key.pem -sha256 -days 3650 -extfile openssl-client.ext
  args:
    chdir: "{{ openvpn_key_dir }}"
    creates: "{{ item }}.crt"

- name: "Register '{{ item }}' client cert"
  slurp:
    src: "{{ openvpn_key_dir }}/{{ item }}.crt"
  register: client_cert

- name: "Register '{{ item }}' client key"
  slurp:
    src: "{{ openvpn_key_dir }}/{{ item }}.key"
  register: client_key

- name: "Generate '{{ item }}' client config"
  no_log: "{{ openvpn_client_config_no_log }}"
  template:
    src: client.ovpn.j2
    dest: "{{ openvpn_ovpn_dir }}/{{ item }}-{{ inventory_hostname }}.ovpn"
    owner: root
    group: root
    mode: 0400
