---
- name: Create openvpn client config file directory
  file:
    path: "{{ openvpn_ovpn_dir }}"
    state: directory
    mode: 0755

- name: Copy openssl client extensions
  copy:
    src: openssl-client.ext
    dest: "{{ openvpn_key_dir }}"
    owner: root
    group: root
    mode: 0400

- name: Register server ca key
  slurp:
    src: "{{ openvpn_key_dir }}/ca.crt"
  register: ca_cert

- name: Register tls-auth key
  slurp:
    src: "{{ openvpn_key_dir }}/ta.key"
  register: tls_auth

- name: Get existing client configs
  ansible.builtin.find:
    paths: "{{ openvpn_ovpn_dir }}"
    patterns: "*.ovpn"
  register: __openvpn_client_cert_find
- name: Generate client keys/ cert
  loop: "{{ clients }}"
  when: "(openvpn_ovpn_dir + '/' + item + '-' + inventory_hostname + '.ovpn') not in (__openvpn_client_cert_find['files'] | map(attribute='path') | flatten)"
  include_tasks: client_keys-keygen.yml

- name: Fetch client configs
  ansible.posix.synchronize:
    mode: pull
    src: "{{ openvpn_ovpn_dir }}/*.ovpn"
    dest: "{{ openvpn_fetch_client_configs_dir }}"
  when: openvpn_fetch_client_configs
